GET http://localhost:5000/todo
# # ---
# POST  http://localhost:5000/todo
# Content-Type: application/json

# {
#     "title":"SECOND",
#     "completed": true
# }
# ---

# PATCH  http://localhost:5000/todo/641d97248d861756e6c5f907
# Content-Type: application/json

# {
#     "completed": false
# }

# DELETE  http://localhost:5000/todo/641d943886f7e63aa09c48b1

GET  http://localhost:5000/section

POST  http://localhost:5000/section
Content-Type: application/json

{
    "title": "VFX"
}



PUT  http://localhost:5000/section
Content-Type: application/json

{
    "section_id": "6420da5748fb98f29a30ccf6",
    "todo_id": "64208d60b45d2a4b74e5a09a"
}


PUT  http://localhost:5000/section/swap
Content-Type: application/json

{
    "section_id": "6420da5748fb98f29a30ccf6",
    "index1": "0",
    "index2": "15"
}

PUT  http://localhost:5000/section/swapSection
Content-Type: application/json

{
    "prevSectionIndex":1
}


DELETE http://localhost:5000/section
Content-Type: application/json

{
    "section_id": "6420da5748fb98f29a30ccf6",
    "todo_id": "6421fa0b4a481cb5ead9297d"
}
6421fabf8c13d0d6c5d6d020
6421fbe0b13903a979dfbcf5
6421fb5cad0c777a7bd9f67a
6421fbfd31171d7a9b9a30fc