GET http://localhost:5000/todo
# # ---
# POST  http://localhost:5000/todo
# Content-Type: application/json

# {
#     "title":"SECOND",
#     "completed": true
# }
# ---

# PATCH  http://localhost:5000/todo/641d97248d861756e6c5f907
# Content-Type: application/json

# {
#     "completed": false
# }

# DELETE  http://localhost:5000/todo/641d943886f7e63aa09c48b1

# PUT  http://localhost:5000/section
# Content-Type: application/json

# {
#     "section_id": "6420da5748fb98f29a30ccf6",
#     "todo_id": "64208d77b45d2a4b74e5a0a0"
# }

GET  http://localhost:5000/section

# DELETE http://localhost:5000/section
# Content-Type: application/json

# {
#     "section_id": "6420da5748fb98f29a30ccf6",
#     "todo_id": "64208d8ab45d2a4b74e5a0a4"
# }
