POST  http://localhost:5000/board
GET  http://localhost:5000/board
GET  http://localhost:5000/board/6421fbfd31171d7a9b9a30fe

# DELETE http://localhost:5000/board/6421fabf8c13d0d6c5d6d023

# PUT http://localhost:5000/board/6421fbfd31171d7a9b9a30fe
# Content-Type: application/json

# {
#     "board_id":"6421fbfd31171d7a9b9a30fe",
#     "section_id": "6421ae7bb982b8f191542208"
# }